package gov.makkah.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 04 23:24:16 AST 2017
// ---------------------------------------------------------------------
public interface testAM extends ApplicationModule {
    void setEmpDeptWithParm(Integer _deptId);
}

