package gov.makkah.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 04 23:18:58 AST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpWithPramImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpWithPramImpl() {
    }

    /**
     * Returns the bind variable value for pDeptId.
     * @return bind variable value for pDeptId
     */
    public Integer getpDeptId() {
        return (Integer) getNamedWhereClauseParam("pDeptId");
    }

    /**
     * Sets <code>value</code> for bind variable pDeptId.
     * @param value value to bind as pDeptId
     */
    public void setpDeptId(Integer value) {
        setNamedWhereClauseParam("pDeptId", value);
    }
}

