package gov.makkah.model.am;

import gov.makkah.model.am.common.testAM;
import gov.makkah.model.vo.EmpWithPramImpl;
import gov.makkah.model.vo.EmpWithPramRowImpl;
import gov.makkah.share.CustomizeAMImpl;

import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 04 23:19:36 AST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class testAMImpl extends CustomizeAMImpl implements testAM {
    /**
     * This is the default constructor (do not remove).
     */
    public testAMImpl() {
    }

    /**
     * Container's getter for Departments1.
     * @return Departments1
     */
    public ViewObjectImpl getDepartments1() {
        return (ViewObjectImpl) findViewObject("Departments1");
    }

    /**
     * Container's getter for Employees1.
     * @return Employees1
     */
    public ViewObjectImpl getEmployees1() {
        return (ViewObjectImpl) findViewObject("Employees1");
    }

    /**
     * Container's getter for Departments2.
     * @return Departments2
     */
    public ViewObjectImpl getDepartments2() {
        return (ViewObjectImpl) findViewObject("Departments2");
    }

    /**
     * Container's getter for Employees2.
     * @return Employees2
     */
    public ViewObjectImpl getEmployees2() {
        return (ViewObjectImpl) findViewObject("Employees2");
    }

    /**
     * Container's getter for EmpDeptFkVL1.
     * @return EmpDeptFkVL1
     */
    public ViewLinkImpl getEmpDeptFkVL1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkVL1");
    }

    /**
     * Container's getter for EmpWithPram1.
     * @return EmpWithPram1
     */
    public EmpWithPramImpl getEmpWithPram1() {
        return (EmpWithPramImpl) findViewObject("EmpWithPram1");
    }
    
    public void setEmpDeptWithParm(Integer _deptId){
        EmpWithPramImpl emp= getEmpWithPram1();
        emp.setpDeptId(_deptId);
        emp.executeQuery();
    }


}

